name: Deploy to EC2

on:
  push:
    branches: [ "main" ]   # Runs workflow when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ===== Backend Build =====
      - name: Install backend dependencies
        working-directory: my-app/backend
        run: npm install

      # (Optional) Run backend tests
      # - name: Run backend tests
      #   working-directory: my-app/backend
      #   run: npm test

      # ===== Frontend Build =====
      - name: Install frontend dependencies
        working-directory: my-app/frontend
        run: npm install

      - name: Build frontend
        working-directory: my-app/frontend
        run: npm run build

      # ===== Deploy to EC2 =====
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/my-app
            git pull origin main
            cd backend && npm install && pm2 restart ecosystem.config.js
            cd ../frontend && npm install && npm run build
